default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: Accelerator
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: shop_test
test:
  <<: *default
  database: shop_development
